/*********************************************************************
 * FileName: HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * Processor: PIC18,PIC24E, PIC24F, PIC24H, dsPIC30F, dsPIC33F, dsPIC33E,PIC32
 * Compiler:  Microchip C18, C30, C32
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 *
 * Microchip licenses to you the right to use, modify, copy, and 
  * distribute: 
 * (i)  the Software when embedded on a Microchip microcontroller or 
 *      digital signal controller product ("Device") which is 
 *      integrated into Licensee's product; or 
 * (ii) ONLY the Software driver source files ENC28J60.c, ENC28J60.h,
 *		ENCX24J600.c and ENCX24J600.h ported to a non-Microchip device
 *		used in conjunction with a Microchip ethernet controller for
 *		the sole purpose of interfacing with the ethernet controller.
 *
 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 *********************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_version(void);
void HTTPPrint_builddate(void);
void HTTPPrint_mis(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_config_gw(void);
void HTTPPrint_config_subnet(void);
void HTTPPrint_reboot(void);
void HTTPPrint_Location(void);
void HTTPPrint_location_Name(void);
void HTTPPrint_cmd(WORD);
void HTTPPrint_conf(void);
void HTTPPrint_pageinfo(void);
void HTTPPrint_ping(void);
void HTTPPrint_breboot(void);
void HTTPPrint_pin(void);
void HTTPPrint_devconData(void);
void HTTPPrint_dat(void);
void HTTPPrint_dtt(void);
void HTTPPrint_v1wave(void);
void HTTPPrint_v2wave(void);
void HTTPPrint_v3wave(void);
void HTTPPrint_c1wave(void);
void HTTPPrint_c2wave(void);
void HTTPPrint_c3wave(void);
void HTTPPrint_wifiSSID(void);
void HTTPPrint_wif(WORD);
void HTTPPrint_wificonStat(void);
void HTTPPrint_cali(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000003:
			HTTPPrint_version();
			break;
        case 0x00000008:
			HTTPPrint_mis();
			break;
        case 0x0000000b:
			HTTPPrint_config_ip();
			break;
        case 0x0000000c:
			HTTPPrint_config_gw();
			break;
        case 0x0000000d:
			HTTPPrint_config_subnet();
			break;
        case 0x00000019:
			HTTPIncFile((ROM BYTE*)"navbar.inc");
			break;
        case 0x0000001c:
			//HTTPPrint_conf();
			break;
        case 0x0000001d:
			//HTTPPrint_pageinfo();
			break;
        case 0x0000001e:
			//HTTPPrint_ping();
			break;
        case 0x0000002a:
			//HTTPPrint_pin();
			break;
        case 0x0000002b:
			//HTTPPrint_devconData();
			break;
        case 0x0000002c:
			HTTPPrint_dat();
			break;
        case 0x0000002d:
			HTTPPrint_dtt();
			break;
        case 0x00000038:
			HTTPIncFile((ROM BYTE*)"foot.inc");
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
